version: '3'

services:
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app_network

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    networks:
      - app_network

networks:
  app_network:
